server:
  port: 8888
  servlet:
    context-path: /collect
spring:
  kafka:
    bootstrap-servers: master:6667,slave001:6667,slave002:6667,slave003:6667,slave004:6667,slave005:6667
    producer:
      # 每次批量发送消息的数量
      batch-size: 16
      # 缓存容量
      buffer-memory: 335544320
      #设置大于0的值，则客户端会将发送失败的记录重新发送
      retries: 0
      # 指定消息key和消息体的编解码方式 UTF-8
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      # 批量消费
      type: batch
    consumer:
      # 每次最多消费条数
      max-poll-records: 100000
      # kafka重复消费
      auto-offset-reset: earliest
kafka:
  #订阅的主题
  topic: topic-jy5
  #主题消费分组
  group: jydata